# Adapted from: https://github.com/marketplace/actions/compile-arduino-sketches
# 
# To customize:
#  - Select which platforms to build and edit the matrix section below
#  - Add library dependencies as needed for this repo in the libraries section below
#
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    strategy:
      matrix:
        include:
          - arch: avr
            fqbn: 'arduino:avr:uno'
            platform-name: 'arduino:avr'
            platform-sourceurl: 'https://downloads.arduino.cc/packages/package_index.json'
          - arch: msp-G2
            fqbn: 'energia:msp430:MSP-EXP430G2553LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_MSP_107_index.json'
          - arch: msp-F5529
            fqbn: 'energia:msp430:MSP-EXP430F5529LP'
            platform-name: 'energia:msp430'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_MSP_107_index.json'
          - arch: msp432
            fqbn: 'energia:msp432r:MSP-EXP432P401R'
            platform-name: 'energia:msp432r'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_MSP432r_index.json'
          - arch: tivac
            fqbn: 'energia:tivac:EK-TM4C123GXL'
            platform-name: 'energia:tivac'
            platform-sourceurl: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_TM4C_104_alternate_index.json'
          - arch: esp8266
            fqbn: 'esp8266:esp8266:thing'
            platform-name: 'esp8266:esp8266'
            platform-sourceurl: 'http://arduino.esp8266.com/stable/package_esp8266com_index.json'
 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: 'jre'
      - run: | 
          if [ ! -f /usr/bin/java ] ; then ln -s $JAVA_HOME/bin/java /usr/bin/java ; fi
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: ${{ matrix.platform-name }}
              version: latest
              source-url: ${{ matrix.platform-sourceurl }}
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            # Add library dependencies here: 
            # - source-url: https://github.com/<owner-name>/<repo-name>.git
            # - name: name-of-library-registered-with-arduino-library-manager
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY

